<%@ Page Language="C#" AutoEventWireup="true"  %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>KISMAT RUMMY</title>
</head>
<body style="background-color:black;">
    <form id="form11" runat="server">
 <asp:ScriptManager ID="ScriptManager1" runat="server">
	</asp:ScriptManager>

<img alt="kismatlogo" style="position:absolute; top: 21px; left: 510px; height: 118px; width: 184px;" src="images/logo.png" />
<h1 style="border-style: none; border-color: inherit; border-width: medium; position:absolute; color: #FFFFFF; font-size: 30px; top: 17px; left: 10px; width: 183px; height: 28px; "> KISMAT </h1>
<h2 style="border-style: none; border-color: inherit; position:absolute; color: #FFFFFF; font-size: 12px; top:144px; left: 536px; height: 18px; width: 126px; "> Terms and Conditions</h2>
 <h1 style="border-style: none; border-color: inherit; border-width: medium; position:absolute; color: #FFFFFF; font-size: 30px; top: 26px; left: 1084px; width: 142px; height: 36px; "> RUMMY </h1>   


<asp:Button ID="Button2" runat="server" BackColor="Black" BorderStyle="Double" ForeColor="White" style="top: 115px; left: 924px; position: absolute; height: 48px; width: 75px" Text="Play Now" 
			PostBackUrl="Index.aspx" />>

<asp:TextBox ID="TextBox1" runat="server" Text="

All products and/or services relating to the games (collectively &quot;Services&quot;) provided to you (&quot;You or &quot;Player&quot;) and offered by Kismatrummy and/or its affiliates, subsidiaries, associates, and partners (hereinafter referred to as &quot;We&quot; or &quot;Us&quot; or &quot;Kismatrummy&quot; or &quot;Our&quot;) through the website https://www.Kismatrummy.com (hereinafter referred to as the &quot;Website&quot;) and the usage of the Website by You is subject to these Terms of Service (hereinafter referred to as the &quot;Terms&quot;).

THESE TERMS SHOULD BE READ BY YOU (THE &quot;USER&quot; OR &quot;YOU&quot; OR &quot;YOUR&quot; OR &quot;PLAYER&quot;) IN THEIR ENTIRETY PRIOR TO YOUR USE OF THE SERVICES.

If any of these Terms is determined to be unlawful, invalid, void, voidable, or unenforceable for any reason by any judicial or quasi-judicial body in India, it will not affect the validity and enforceability of the remaining Terms. Any unlawful, invalid, void, voidable, or unenforceable Term will be replaced with another Term that is valid and enforceable and most nearly gives effect to the original intent of the invalid /unenforceable Term.

By registering, You are deemed to have accepted and understood all the Terms. We recommend that You print out (or save to file) all transaction records, rules of play, cancellation policies, and pay-out policies.

Our failure or delay to act or exercise any right or remedy with respect to a breach of any of these Terms by You does not waive Our rights to act with respect to any prior, concurrent, subsequent or similar breaches.

If a competition or tournament is organized by Us on the Website, it shall be governed by these Terms and any supplementary terms and conditions which may be specifically applied for a competition or tournament.

If You do not agree to the following Terms or any future alterations or modifications to these Terms, You may discontinue use of the Website and any Services offered by it.

    ACCOUNT CREATION: USER ACCOUNT, PASSWORD AND SECURITY
        You are required to register initially to avail of the Services and to start playing the games. This will include providing Kismatrummy with your current, complete, and accurate information as may be required by Kismatrummy.
        Click on the &quot;Sign up&quot; button on the home page or use the quick registration form on the home page to complete the registration. Note that Play Nowg up confirms Your acceptance of these Terms.
        You are required to furnish information like a &quot;Log-in&quot; name (or user name), password and a valid email address. Your Log-in name must be unique and cannot be vulgar or otherwise offensive (as determined by Kismatrummy at its sole discretion). It shall not infringe any trade mark or other proprietary rights of a third party. Your Log-in name can only be used in accordance with these Terms and/or other applicable agreements. We suggest that You use a unique Log-in name and a unique and secret password.
        Your membership or subscription is personal to You. You are advised not to transfer or make available Your account name and password to others and not to use anyone else's account at any time. You are entirely responsible for maintaining the confidentiality of Your password and account and You have sole responsibility for any and all activities that occur through Your account. In the event of any unauthorised use or theft of Your account or any other breach of security, You must immediately notify Kismatrummy of such event. If required and/or requested, You agree to provide Kismatrummy with evidence of such theft or unauthorised use.
        Kismatrummy will not be liable for any loss that You may incur as a result of any unauthorised use of Your account by another or as a result of someone else using Your password or account, either with or without Your knowledge.
        You acknowledge that at any point in time, We may require You to verify the correctness of the information provided to Us. We may require You to provide Us with additional contact information and You hereby agree that You may be required to provide Us with such additional contact information during the registration process or after You have registered with Us. Kismatrummy reserves the right to cancel, suspend or terminate Your account in case of any violation of the Terms.
        You are restricted from uploading and distributing sensitive information like the passwords and Log-in name (user-name) on the web.
        You are required to treat fellow players with respect and courtesy throughout your use of the Website. In the event it is found by Us, or a complaint is received by Us from your fellow players, to the effect that You have been offensive and / or abusive towards Your fellow players, We shall be fully entitled to cancel, suspend or terminate Your account
        You agree to indemnify and hold harmless Kismatrummy from any claim, demand, damage, or loss including reasonable attorneys' fees, asserted by any third party, due to or arising out of Your use of the Services or arising out of use by any third party of the Services using Your account.
        We do not allow multiple accounts and only one account is allowed per house hold.
    ACCOUNT VALIDATION:
        Kismatrummy reserves the right to validate players' accounts. These attempts may be made via phone call or email.
        We reserve the right to stop players from logging in into the Website, if the validation is unsuccessful.
        You may be required to provide proof of Your identification at any given time. The information provided is kept confidential and can be used only for internal purposes to confirm the authenticity of the account created.
    CONTENT AND SOFTWARE:
        Kismatrummy shall be the owner or authorized user of all content and material on the Website including but not limited to information, images, marks, logos, multimedia clips, animation, games and software (collectively referred to as &quot;Content, other than personal information of Users posted by them in order to avail of the Services. &quot;).Content posted by Kismatrummy may be protected by applicable intellectual property laws.
        Kismatrummy is the owner or authorized user of all software programs forming part of the Website (www.Kismatrummy.com). You acknowledge that you may only make use of the Website for the purpose of availing of the Services and not for any commercial purposes or for Your profit (other than through the Services). Provision of the Services shall not be deemed to provide you with a license to use the software embedded in the Website for any purpose other than to avail of the Services. You shall not have any right to reverse engineer, disassemble, decompile, use for purposes unconnected with the Services or otherwise interfere with the working of such software.
        You shall not attempt to &quot;hack&quot; into the Website or obtain access to the source code of the software or to any links in the Website that are not meant to be accessed by You in the regular course of Your use of the Services.
        In the event it is found by Us that attempts to reverse engineer, disassemble, decompile or hack into the Website have been made by You, You shall be liable to be prosecuted by Kismatrummy under the applicable laws.
    PRODUCT OFFERING: Competitions and tournaments organized by Us on the Website may be of several types including Cash Tournaments, Promotional Tournaments, and Practice Tournaments.
        Practice Games:
            Practice Tournaments are conducted to familiarize players with various games and rules of tournament play.
            You understand and agree that if You win a Practice tournament, You do not receive any actual prizes or cash.
            You may not hold Kismatrummy responsible for not being able to play a tournament for which You may be eligible. This includes but is not limited to situations where You are unable to log into Your account, due to Your account being under validation or You being in violation of any Terms or there being any disruption from your internet service provider.
        Promotional Tournaments:
            The Promotional Tournaments organised on the Website shall be either free to join or may require You to use Your promotional chips that You accumulate while playing Promotional Tournaments.
            The chips that You win in a Promotional Tournament can only be utilized by redeeming them for gifts and prizes that are offered by Kismatrummy at its discretion.
            The chips won in Promotional Tournaments cannot be redeemed for cash.
            The details of Promotional Tournaments may vary from time to time and Kismatrummy shall make its best efforts to publish this information on the Website and additionally inform the relevant players via e-mail, or other means of communication but does not guarantee the same.
            You may not hold Kismatrummy responsible for not being able to play a tournament for which You may be eligible. This includes but is not limited to situations where You are unable to log into Your account, due to Your account being under validation or You being in violation of any Terms or there being any disruption from your internet service provider.
        Cash Tournaments:
            Some tournaments may require You to pay a BuyIn or entry fee, as described in the specific supplementary terms and conditions, which govern those tournaments.
            The amount of BuyIn or entry fee may differ from tournament to tournament at the sole discretion of Kismatrummy.
            Any applicable tax, levy or cess for any prize which You may win will be borne by You.
            We reserve the right to retain any amount from prizes or gifts as We may be required to pay as tax, as required by the applicable laws of India.
            Your participation in tournaments and games made available on the website which require You to pay &quot;BuyIn&quot; or entry fees is subject to the additional following terms and conditions:
                You must be 18 years of age or above to participate in paid games, tournaments and competitions offered on Kismatrummy and must truthfully state Your age while registering with Us. We absolutely prohibit minors or those underage from participating in any of the games, tournaments and competition. We reserve the right to ask for proof of age from You and suspend Your account until satisfactory documentation is provided. Should We have reason to believe that You are less than 18 years of age, You will not be allowed to participate in any paid games, tournaments and competitions and your account will be deactivated.
                All transactions for cash tournaments and games will be calculated in Indian rupees.
                Once You register on Our Website, We shall maintain an account for You to keep a record of all Your transactions with Us. Payment of BuyIn/entry fees for any game/tournament has to be made through Your account. All cash prizes won by You are credited by Us into Your account.
                We may specify maximum and minimum limits in the respect of the amount of money that you may be required to purchase in Your account for the purpose of paying BuyIn/entry fees as prescribed to participate in cash tournaments.
                When making a payment, you are advised to ensure that the instrument used to make the payment is Your own and is used to add cash in Your cash account. You may not:
                    Use any payment instrument that You are not authorized to use, to transact on Kismatrummy.
                    Use Your payment instrument to transact on Kismatrummy using an account which does not belong to You.

                NOTE: In the event of any violation of the above, We reserve the right to fully investigate the matter, if necessary report the matter to appropriate authorities, and close Your account instantly. We reserve the right to retain the funds in Your account without applying them for the purpose for which they are paid, until We have suitably identified the source of payment and confirmed that the payment has been validly made or with due authorization.
                When You make a payment on the Website using any of the available modes of payment, Your payment is processed by a third party payment gateway and any information entered by You in this regard on such gateway is not visible to Us.
                You understand and agree that We have the right to cancel a transaction at any point of time solely according to Our discretion, without asPlay Nowg any reasons. In the event that You have made any payment for which You have received no benefit, the transaction will be reversed and the money would be credited back to Your payment instrument.
                You also understand and agree that a payment made through any mode of payment available on the Website may be rejected by the payment gateway for reasons independent from Our own. You acknowledge and agree that Kismatrummy is not liable for any such non-processing or rejection of the payment for reasons not attributable to or beyond the control of Kismatrummy.
                Kismatrummy assures You that any money held in Your account with Us paid by You or which may have accrued to You under these Terms is held in the nature of a trust with Us and will be utilized for the purpose of the Services or remitted to You, as the case may be in due course. You acknowledge and agree that the monies deposited / paid by You in Your account shall not accrue interest.

                Kismatrummy advises You to play responsibly on the Website. Kismatrummy may therefore, from time to time, place restrictions on the amount of money You can add to Your Kismatrummy account, which You can spend as entry fee in various tournaments and games hosted on the Website.

                You acknowledge, understand, and agree that Your participation in the various tournaments and games available on the Website will be subject to conditions regarding purchase of chips and that You will neither dispute nor question the same. Note that you can buy a minimum of 100 cash chips and a maximum of 20000 cash chips using our available payment options. This upper and lower limit for cash chips maybe altered by Kismatrummy at any time without giving a prior notice for the same.
                You can choose to leave the table from a cash tournament by clicking on &quot;Leave the Table&quot; before registration for that tournament closes, and in such case Your entry fee will be credited back to Your account. Once registration for a tournament closes, no refund is possible and You shall not demand the same.
                You understand and agree that once You join a tournament, the entry fee for that tournament will be debited from Your Kismatrummy cash account as a valid payment for Your participation in that cash tournament. If You subsequently choose to redeem from the cash tournament before registration close time, the entry fee will be credited back to Your Kismatrummy cash account.
                Any cash prize won by You will be credited to Your Kismatrummy account. You agree that all cash-outs You make are governed by the following conditions:
                    You can choose to redeem money from Your account at any time subject to bonus cash-outs restrictions, as mentioned hereafter and notify Us of the same. Once notified, We may disburse the specified amount by cheque or electronic transfer based on the mode of cash-outs selected by You. We shall make Our best efforts to honor Your choice on the mode of cash-outs, but reserve the right to disburse the specified amount to You by any means as may be determined by Us.
                    You can make two free cash-outs in a calendar month. Any subsequent/additional cash-outs requests within the same month will attract applicable processing and service charges/tax which will be deducted from Your account. In the event that You do not have an adequate amount in Your account to pay the processing charge, Your cash-outs will not be processed at that time. You are free to request a cash-out in the subsequent month, which will not be charged provided it is within your free cash-outs limit.
                Your registration details including Your name, using which You have registered on the Website, must correspond with the name and other details on Your financial instrument used on the payment system. If this is not the case, We reserve the right to verify Your details to ensure that the financial instrument used for the transactions is not being misused. In this regard:
                    We may verify Your identification details and age from time and time.
                    At any point of time in Our transactions with You, if We detect or have reasonable cause to suspect that You may be involved with identity fraud, We may withhold the purchase in Your account and bar You from further participation in any tournament available on Kismatrummy without prejudice to any other legal recourse We may have apart from notifying the relevant regulatory or law enforcement authorities where appropriate.
            Your participation in tournaments or games made available on the Website and any prize(s) You may win in such tournaments/games signifies that You agree and consent to the following:
                Your registration on the Website is restricted to a single user account, which will be used by You to avail of the Services provided on the Website.
                You are prohibited from creating or using multiple user IDs for registering on the Website. If We have reason to believe that You have created multiple user IDs, We reserve the right to suspend Your account(s) until We have investigated the matter and have received adequate supporting documents from You. We reserve the right to close all the additional accounts created by you and forfeit all the cash balances present in your multiple accounts. In addition, We reserve the right to ask for verification documents from You.
                You undertake to participate in the games/tournaments as an individual player.
                Formation of teams and collusion between You and any other user(s) for participating in games/tournaments organized on the Website is expressly forbidden and will result in Us cancelling the relevant accounts and debarring access to the Services for all users, who are members of such teams or have taken part in such collusion. By accepting the Terms, You agree that You will not play the games in partnership or by forming a team or by communicating with other players which may give undue benefit to You or other players. In case You are found to be involved in such activities, We reserve the right to withhold all the funds in Your account and make investigations to ascertain the extent of undue benefit derived by You and such others and to cancel and close Your account without any communication to You.
                You undertake that You Yourself will play in all games/tournaments in which You have registered, and not use any software programs, bots, devices or any other form of external assistance to play. Any attempt to employ any such external assistance will result in You being debarred from further participation, cancellation of Your registration with Us, and possible forfeiture of Your cash balance.
                You agree and acknowledge that We will take all steps necessary to determine whether Your participation is in accordance with the Terms laid down herein.
                We may debar You from participation in any game/tournament organized by Us, suspend Your account, prohibit Your access to the Website and withhold any prizes that You may have won, should We have reasonable grounds to suspect that: You have indulged in any fraudulent activity; or have registered or have availed of the Services provided on the Website using multiple user IDs or you have breached any of the Terms.
                In the event of a disagreement or dispute between You and any other user(s) in a game, Our decision shall be final and binding on you and the other user(s).

                Subject to paragraph VII below, to be eligible to win a prize, You must be a resident of India and You must have accessed the Services and the Website from India.

                If You are a prize winner, resident in India and physically present in India while accessing the services of Kismatrummy but not an Indian citizen, We will remit Your winnings in Indian Rupees to the address provided by You for playing cash tournaments provided the address is within India. There may be, in such events, delays which You may find inordinate. You, however, agree and acknowledge that such delays may not be within Our control and that You will wait for us to obtain necessary clearances and permissions for such remittances.
                Any prize You win, accrues solely to You and will not be assigned or transferred to any third party by Us.
                If You are not a resident of India or do not access the Website from India, You are prohibited from participating in cash or promotional tournaments on Kismatrummy. Your participation in such tournaments will be deemed to be in violation of these Terms. Subsequently, You will not be entitled to receive any prize that You might win in such tournaments. We shall have the right to fully investigate the matter, report the matter to appropriate authorities, and to take appropriate legal action.
                If any prize is handed over to you in the form of a cheque and the cheque is not encashed within the validity period of the cheque, We will deem the cheque to have been lost. Any request for re-issue of the cheque will be approved or rejected at our discretion and if approved, will result in deduction of applicable processing charges from the amount of the cheque on re-issuance.
                We do not take any responsibility for who You are matched up against in a tournament or at any time during which a tournament is in progress. The matching is done based on predefined and random computer generated criteria, which apply uniformly to one and all playing on the Website. As a result, it is not within Our control to match specific players against each other.
                You agree and acknowledge that We shall not be responsible for whom You play with in a tournament and that You will not request a change to or reversal of the outcome of the tournament based on the identity of your opponents or other players.
    SERVICE CHARGE AND SERVICE TAX:
        We currently levy a service charge of 15% on all games and 12% for strikes games on the BuyIn/entry fees paid by You for participating in cash games/tournaments available on the website.
        The service charge levied is subject to change from time to time and We shall post notice of the same as soon as is feasible. We reserve the right to levy service charge at different rates for different cash tournaments/games organized by Us.
        In addition, we may charge service tax with applicable cesses or levies on Our Services to the Users as mandated by applicable laws in India.
    TELL A FRIEND:
        You may invite a friend, acquaintance, or any other person to use the Services available on the Website by clicking the appropriate links given in the Website. Just choose Your email provider or social networking site(s) and invite Your friends to join Kismatrummy. All Your personal information is kept private and is not disclosed to anyone.
        When You invite Your friends or acquaintances to subscribe to the Website through the &quot;Tell a Friend&quot; feature, Kismatrummy uses third party websites to import Your address book containing the email addresses of such friends and acquaintances to which You can then choose to send invitations.
    SERVICES NOT OFFERED IN Assam and Orissa:
        Applicable laws in Assam and Orissa may result in penalties being imposed on players, who access the Services from these states. We do not accept applications from players from those states for participating in any game or competition available on the Website.
        You accept that We do not take any responsibility for Your breach of any applicable state laws and You are advised to ascertain whether access to Our Services would result in violation of any law applicable in the state from which You gain access to the Services.
        Should We come to know or have reasonable cause to believe that You are participating in any tournament available on the Website, from Assam and Orissa, or from any other state where making use of the Services may be deemed illegal, We reserve the right to immediately and without further notice to You, terminate Your account with Us and remit the entire balance in Your account back to You after deduction of applicable processing charges. You understand and agree that Our decision in this regard is final. You agree that Kismatrummy shall not be responsible for any breach committed by you under the applicable laws of the state from where you access / try to access the Website.
    PLAYER RESPONSIBILITIES:
        You are held legally responsible and liable for all of Your activities on the Website from Your Log-in account (or user ID).
        By viewing or using the Website or availing of any Services including multi-player games, or using communication services including but not limited to chat rooms, email services or any other real time or non-instant messaging facility provided by the Website.
        Players acknowledge that they may be exposed to content posted by other users which they may find offensive, objectionable or indecent and that Kismatrummy may not be able to prevent such content being posted.
        Players are requested to bring such content posted by other users to Our notice that they may find offensive, objectionable or indecent. Kismatrummy shall remove or act upon such information in the manner as provided in paragraph I (8) above or as it may deem fit.
        The decision taken by the management on this regard shall be final and binding on the Player and the Player specifically agrees that Kismatrummy will not incur any liability under any circumstance whatsoever regarding the same.
        You understand and agree that We do not take any responsibility and will not be liable for any consequence that might arise as a result of You sharing Your personal information or any other information through Our communication services including but not limited to game chat, email services, or any other real time or non-instant messaging facility provided by the Website.
        You understand that it is Your responsibility to protect the information You provide on the website including but not limited to usernames, passwords, email addresses, contact details, and telephone numbers. You specifically understand and agree that We will not incur any liability for information provided by You to anyone which may result in Your account on the Website being exposed or misused by any other person or any other harm or loss being suffered by You.
        You are liable to comply with any applicable law, while taking part in any competition or tournament organized through the Website. You undertake and agree to indemnify Us against any claims, expenses or liabilities suffered by or claimed against us by any person or entity arising out of Your non-compliance with any applicable laws.
        You also understand and accept that Your mere participation in a game/tournament available on the Website does not create any obligation on Us to give You a prize.
        Your winning a prize is entirely dependent on Your skill as a player vis-a-vis other players in the game/tournament and subject to the rules of the game/tournament. To learn more about the rules, please visit Support section on Kismatrummy. Please read the same thoroughly before proceeding to participate in any game/tournament available on the Website.
        You acknowledge that Your participation in any game/tournament available on the Website is purely voluntary and is at Your sole discretion and risk.
        You understand and acknowledge that once a game/tournament has commenced, Your not being able to play due to slow internet connections, faulty hardware or for any other reason not attributable to Us does not entitle You to a refund of the entry fee You may have paid for participation.
        You agree, understand and acknowledge that You will use Your account with Us solely for the purpose of playing on the Website and for any other transactions with Us which You may have to carry out with respect to Your usage of the Services.
        Use or attempted use of Your account with Us for any reason other than as stated above will result in immediate termination of Your account and forfeiture of any prize, bonus, or balance accrued to you or in Your account. Additionally, We reserve the right to bar You from future registration or participation on the Website.
        You understand and acknowledge the fact that We are neither a bank nor a financial institution and that the purchases/balance standing to the credit in Your account do not accumulate any interest. You also understand and agree that Your account maintained with Us is purely for the purpose of payment of the entry/subscription fee to participate in games/tournaments made available on the Website and for purchase of cash prizes which You may win.
        You understand and agree that You cannot transfer any sum from Your account with Us to the account of another subscriber / player / registrant on the Website.
        The Company is obligated to deduct tax at source (&quot;TDS&quot;) in case of winnings of Rs. 10,000/- or more in a single game or Points Rummy Game or a tournament, as the case may be. In such cases, winnings shall be credited to your Account after deducting TDS @ 30%. Please note that you must possess a valid PAN and provide your PAN details and proof thereof immediately upon request, in order to enable us to credit such winnings and allow for Cash Withdrawals in this respect. These requirements and provisions may be modified from time to time in accordance with changes to the relevant tax and other laws.
        You understand that the Internet may be an unreliable medium and it is possible that You may not be able to play on the Website due to technical reasons. You acknowledge and agree that Kismatrummy is not liable for any downtime, server disruptions, lagging, or any technical disturbance during your usage of the Services.
        You further understand, acknowledge and agree to the fact that if You are unable to play in any paid tournament after payment of entry/subscription fee or if a game or tournament is unable to be completed due to any error or omission attributable to Kismatrummy, Your remedy is limited either to:
            A refund of the amount of subscription/entry fee, which You actually paid for participation; or
            Free participation in a like value tournament as decided by Kismatrummy.
        You understand and agree that if a game or tournament is unable to be completed for any reason other than a reason attributable to Kismatrummy's error or omission, Kismatrummy shall not be liable for any claim that You may have for potential prizes.
        You acknowledge that You are making use of the Services with the knowledge that You face a risk of monetary loss, when using the Services and that Kismatrummy shall have no responsibility to You for any such loss that arises in the course of your participation in the Services.
        You agree that under no circumstances shall Kismatrummy be liable to pay you any amount over and above the subscription/entry fee.
    RESTRICTIONS ON PLAYERS:
        You shall not Yourself or through a third person or through any automated program commit any act, implied or express, which violates any intellectual property right including copyright and trademark rights in any Content. You may not reproduce any of the Content on the Website without obtaining specific written permission from Us. You shall not post, distribute, or otherwise make available or transmit any data, text, message, computer file, or other material that infringes and/or violates any right of a third party or any domestic or international law, rule, or regulation, including but not limited to: (a) copyright, patent, trademark, or other proprietary rights; (b) right of privacy (specifically, You must not distribute another person's personal information of any kind without their express permission) or publicity; (c) any confidentiality obligation.
        You shall not frame the Website. You shall not impose editorial comments, commercial material, unsolicited information or emails or any information on the Website or alter or modify Content on the Website, or remove, obliterate or obstruct any proprietary notices or labels.
        You shall not use the Content on the Website for commercial purposes including but not limited to use as or in a cyber cafe, computer gaming center, network play over the Internet or through gaming networks or connection to an unauthorized server that copies the gaming experience of the Website.
        You shall not advertise or sell any products, services or otherwise (whether or not for profit), or solicit others or use the forum of the Website for commercial purposes of any kind.
        You agree that You will not post or transmit through chat/community rooms or in any manner on the Website any defamatory, threatening, obscene, harmful or pornographic material or material which would violate or infringe in any way upon the rights of others (including intellectual property rights, rights of confidentiality, or rights of privacy) or cause offense, distress or inconvenience or which do not comply with all relevant laws.
        You will not upload, distribute, or publish through the Website, content which may contain viruses or computer contaminants (as defined in the Information Technology Act, 2000 in force in India and as may be amended from time to time) which may interrupt, destroy, or limit the functionality or disrupt any software, hardware, or other equipment belonging to Us or that aids in providing the services offered by Kismatrummy.
        You shall not, through any service or facility including any instant or non - instant messaging facility provided by the Website, promote the Services of any third party including websites which may be providing Services similar to Kismatrummy.
        You shall not intentionally disrupt other users or discussions by repeatedly posting the same message or through excessive posts.
        You may not impersonate another person or user, attempt to get a password, other account information, or other private information from a user, or harvest email addresses or other information. In the event We have reasonable grounds to believe that Your actions include any of the acts specified above, We may initiate appropriate legal proceedings against You as well as notify the relevant regulatory or law enforcement authorities where appropriate, apart from suspending or terminating Your privileges for the use of the Website.
        You may not host, intercept, emulate or redirect proprietary communication protocols, if any, used by the Website regardless of the method used, including protocol emulation, reverse engineering, modifying the Website or any files that are part of the Website.
        You may not add unauthorized components, create or use cheats, exploits, bots, hacks or any other third-party software designed to modify the Website or use any third-party software that intercepts, mines or otherwise collects information from or through the Website or through any Services. You may not upload or post any content on the Website other that content that you are required to post or upload in order to avail of the Services.
        You may not purchase, sell, trade, rent, lease, license, grant a security interest in, or transfer Your user account, any Content, currency, points, standings, rankings, ratings, or any other attributes appearing in, originating from or associated with the Website or by using any Services.
        NOTE: In addition to the right to initiate appropriate legal proceedings against You as well as notify the relevant regulatory or law enforcement authorities, We reserve the right to remove and delete any objectionable material and content from the Website.
    PLAYER REPRESENTATIONS:
        Players are required to undertake that they will not allow any other person to play from their accounts or using their user name and password.
        Players are expected to understand and agree that they are solely responsible for all content posted, transmitted, uploaded or otherwise made available on the Website by them.
        Players certify that they own the intellectual property rights in all such content.
        Each Player specifically agrees to indemnify, save and hold harmless and defend Us (to the extent of all benefits and awards, cost of litigation, disbursements, and reasonable attorney's fees that We may incur in connection therewith including any direct, indirect or consequential losses, any loss of profit and loss of reputation) from any claims, actions, suits, taxes, damages, injuries, causes of action, penalties, interest, demands, expenses, and/or awards asserted or brought against Us by any person claiming infringement of their intellectual property rights by that Player.
        By submitting content to the Website, each Player agrees to grant Us a royalty-free, world-wide, non-exclusive, perpetual, and assignable right to use, copy, reproduce, modify, adapt, publish, edit, translate, create derivative works from, transmit, distribute, publicly display, and publicly perform such Content (other than names, contact information and passwords of Players) and to use such Content in any related marketing materials produced by Us or Our affiliates.
        Players understand that they do not obtain any rights, legal or equitable, in any material incorporating the Content.
        Each Player declares that he/she shall not assert any moral rights in the Content at a later date.
        Each Player acknowledges that Kismatrummy shall not be responsible for the telecommunications networks and internet access services required for access to and use of the Services.
        Players are solely responsible for any applicable taxes which may be payable on winnings paid to the Players.
        Players agree that the use of the Services is at their sole option, discretion and risk.
    ACCOUNT CLOSING / SUSPENSION / TERMINATION:
        You are free to discontinue Your use of the Website at any time by intimating Us of Your desire to do so by an email sent to Us at &quot;account@Kismatrummy.com&quot;. If at that time, there is a positive balance in Your cash account, We will pay you the balance by a cheque or through any other means as may be determined by Us in a timely manner. Further, We reserve the right to collect fees, surcharges or costs incurred before You cancel Your account or a particular subscription.
        We may discontinue Your registration with the Website, suspend or terminate Your access to the Services at Our sole discretion at any time without giving You prior notice, in the event that We have reasonable grounds to believe that You are in breach of any of the Terms specified herein.
        You agree that, subject to applicable law, You may be liable to forfeit any money lying in Your account with Us in the event of any breach of these Terms. Without prejudice to the aforementioned facts, We may also initiate appropriate proceedings against You in accordance with applicable laws.
        Kismatrummy reserves the right to bar You from using the Website if We have reasonable ground to believe that You have provided access to Your account to someone other than Yourself or that You have created an account for the purpose of allowing someone other than Yourself to play on the Website using the account created.
        We reserve the right to bar You from using the Website, if We have reasonable ground to believe that You may have intentionally impersonated another individual by providing details which are not Your own while registering on the Website. We further reserve the right to initiate civil and/or criminal proceedings against You for such impersonation and misuse of another individual's personal or financial information on Our Website by You.
        Kismatrummy reserves the right to suspend and/or terminate Your account or access to money in it for a number of reasons which Kismatrummy may deem fit, including but not limited to the following:
            Where, We have reasons to believe that the security of Your account has been breached; or
            Your account is being used for any unlawful activity or fraudulent purpose (including money laundering); or
            if there have been charge-backs on Your account; or
            if We have reason to believe You are involved in collusion or cheating of any kind; or
            You are under 18 years of age; or
            You are in a jurisdiction that renders the provision of Our Services to You or Your use of them illegal.
        If You provide information which is not truthful to the best of Your knowledge, incorrect information or conceal relevant information regarding Your address/residence, thus violating the Terms, or in case We have reasonable grounds to believe that You have provided incorrect information and are playing from locations where playing tournaments as available on the Website is not permitted, We reserve the right to immediately and without further notice to You, terminate Your account with Us and remit the entire balance in Your account back to You after deduction of applicable processing charges.
        Fraudulent activity shall include::
            using credit card(s), debit cards, net-banking usernames, passwords, authorization codes, prepaid cash cards, mobile phones not belonging to You or without permission of the owner of the above mentioned instruments to make payments,
            impersonating another person; or
            accessing another User's account without authorization.
        In case of termination of Your account due to Your breach of these Terms, We may retain the balance in Your account if entitled to do so till the end of due legal process for mitigation of the fraud. This will be without prejudice to other statutory proceedings, We may initiate in accordance with the appropriate law currently in force in India.
        NOTE: We will try and complete any investigations and deal with the cause of any suspension as soon as practicable in the context of any legal or regulatory obligations that We may have but until that is done, We may continue suspension or opt to close the account at Our sole discretion. We can also put a suspension in place or close Your account at any time (as We may determine at Our discretion).
        The decision of Kismatrummy.com management is final and binding in case of any disputes.
    MODIFICATIONS AND ALTERATIONS:
        Kismatrummy reserves the right to alter or modify these Terms at any given time without giving prior notice to You. Your use of the Website and/or any Services offered constitutes Your unconditional acceptance of these Terms.
        Kismatrummy reserves the right to suspend, add, modify or discontinue any or all Services available on the Website at Our sole discretion at any time without giving You prior notice.
        In such an event, You agree and acknowledge that We will not incur any liability in this regard, either to You or any third party.
    DISCLAIMER AND INDEMNIFICATION:
        Kismatrummy expressly disclaims all warranties or conditions of any kind, express, implied or statutory, including without limitation the implied warranties of title, non-infringement, merchantability, and fitness for a particular purpose.
        The Website &quot;www.Kismatrummy.com&quot; and the Content present on it are provided strictly on an 'as is where is' basis with any faults or failings and any representation, warranty, condition or guarantee whatsoever, expressed or implied (including, without limitation, any implied warranty of accuracy, completeness, uninterrupted provision, quality, merchantability, fitness for a particular purpose or non-infringement) is excluded to the fullest extent permitted by law. Kismatrummy does not ensure or guarantee continuous, error-free, secure or virus-free operation of www.Kismatrummy.com or its content including software, games, Your account or continued operation or availability of any facility on www.Kismatrummy.com.
        Additionally, Kismatrummy does not promise or ensure that You will be able to access Your account whenever You want. It is entirely possible that You may not be able to access Your account or the Services at times or for extended periods of time due to, but not limited to system maintenance and updates.
        You agree that You are aware that participation in the games of skill organized by Us may result in financial loss to You. With full knowledge of the facts and circumstances surrounding the activity, You are voluntarily participating in such activity and assume all responsibility for and risk resulting from, Your participation, including all risk of financial loss. You agree to indemnify and hold Kismatrummy, its employees, directors, officers, and agents harmless with respect to any and all claims and costs associated with Your usage of the Website.
        5. You acknowledge that You are solely responsible for any action that arises from Your participation and /or with usage of the Website , regardless if occurring before, during or after the period of such usage.
        To the extent permitted by law, and in consideration for being allowed to access the Website, You hereby save, hold harmless, discharge and release Kismatrummy from any and all liability, claims, causes of actions, damages or demands of any kind and nature whatever that may arise from or in connection with Your usage of the Website.
        You recognize and acknowledge that Kismatrummy makes no guarantees, warranties, representations, or other promises related to usage of the Website, and assumes no liability or responsibility for any financial loss that You may sustain as a result of participation in the Activity.
        You agree to assume the entire risk as to the results and performance of any software and/or games availed by You on www.Kismatrummy.com as such result and performance among other things depends on Your Internet connection and hardware. You also assume the entire cost of all servicing, repair and/or correction of Your hardware when You access, download or execute software or games available on www.Kismatrummy.com. Kismatrummy expressly disclaims liability for any delay or failure of Your computer or equipment in performance resulting from installation of Kismatrummy's games or software on Your computer.
        Kismatrummy disclaims responsibility and liability for any harm resulting from cancellation of tournaments organized by it. If You are a cash player on www.Kismatrummy.com, You acknowledge and agree that You will not be refunded in case of any service outages that may be caused by failures of service providers, computer viruses or contaminants, or any other cause beyond the reasonable control of Kismatrummy.
        Under no circumstances (including, without limitation, in contract, negligence or other tort), shall Kismatrummy be liable for any indirect, incidental, ancillary, special, punitive or consequential damages arising out of the use of or inability to use www.Kismatrummy.com even if We have been advised or become aware of the possibility of such damages or loss or that such loss was foreseeable. You agree to indemnify Us against any claims in respect of any such matter. Kismatrummy's liability to you shall in no event exceed the fees paid by you for entry into the game or tournament in connection with which such liability arose and/or the amount of any monetary prize that You may win upon due completion of a game or tournament.
        You specifically acknowledge, agree and accept that We are not liable to You for:
            defamatory, offensive or illegal conduct of any other player or for anything that turns out to be misleading, inaccurate, defamatory, threatening, obscene or otherwise illegal originating from another player or a third party;
            any loss whatsoever arising from the abuse or misuse of Your account on Our Website;
            any loss incurred in transmitting information from or to Us or from or to Our Website by the internet or by other connecting media;
            any technical failures, system breakdowns, defects, delays, interruptions, manipulated or improper data transmission, loss or corruption of data or communications' lines failure, distributed denial of service attacks, viruses or any other adverse technological occurrences that You suffer arising in connection with Your access to or use of Our Website;
            the accuracy, completeness, or currency of any information services provided or any statistics shown on the Website;
        Certain Services or events including tournaments made available or organized on www.Kismatrummy.com may require specific permission from statutory or regulatory bodies in India. Such Services or events shall stand cancelled or deemed to be cancelled if such permission is denied or if such Services are later forbidden, whether before or after such Services or events have commenced or have been completed. Such Services or events shall also stand cancelled if disallowed by any process of a competent judicial, administrative or regulatory authority. In such an event, You shall not be entitled to any damages, demands, refunds or claims of any nature.
        You agree to indemnify, defend and hold Kismatrummy harmless from all claims, damages and expenses made by any third party arising out of
            Your content, or
            Your use of www.Kismatrummy.com, Your connection to www.Kismatrummy.com, or
            Your violation for these Terms or Privacy Policy; or
            use of www.Kismatrummy.com by any other person accessing Your usernames or password, with or without Your authorization.
        We as a merchant shall be under no liability whatsoever in respect of any loss or damage arising directly or indirectly out of the decline of authorization for any monetary transaction, on account of the cardholder having exceeded the preset limit mutually agreed by Us with our acquiring bank from time to time.
    GOVERNING LAW; DISPUTE RESOLUTION; JURISDICTION:
        The Terms shall be governed and interpreted by, and construed in accordance with the laws of India. All disputes, differences, complaints etc., shall be subject to arbitration under the (Indian) Arbitration and Conciliation Act, 1996 as amended from time to time. The place of arbitration shall be Hyderabad, Andhra Pradesh, India and the language of arbitration shall be English. Arbitration shall be conducted by a sole arbitrator to be appointed by Kismatrummy and the concerned Player.
        Subject to the arbitration agreement above, all disputes, complaints, differences etc. shall be subject to the exclusive jurisdiction of the courts at Hyderabad, Andhra Pradesh, India.
        DISCLAIMER: People from many jurisdictions access the internet. We endeavour to stay current with the laws in every jurisdiction; however, there may be instances where, We do not receive prompt updates for every such jurisdiction. Please make sure that any activities you engage on the Website are legal where you live. You agree to indemnify and hold harmless Kismatrummy from any claim, demand, damage, or loss including reasonable attorneys' fees, arising out of Your non-compliance with the laws of Your jurisdiction.
    PHONE NUMBER/EMAIL CHANGING PERIODS:
        First Time : Initially the phone number/email can be changed at any time whenever player wishes to change for the account.
        Second Time : After you have changed the number for first time, you have the option of changing phone number/email change second time after minimum of 15 days to your first change.
        Third Time : You have the option of changing phone number/email for third time after minimum of 30 days to that to your second time change.
        Fourth Time : You have the option of changing phone number/email for fourth time after minimum of 90 days to that to your third time change.
"  style="top: 160px; left: 0px; position: absolute; height: 432px; width: 1214px" TextMode="MultiLine"></asp:TextBox>
		
		
		<asp:UpdatePanel ID="UpdatePanel1" runat="server">

	

		</asp:UpdatePanel>



    </form>
</body>
</html>
